### ISSUE TITLE
Example to work with this

### ISSUE THREAD

**Issue by cberenguer** [arslanmughal99/angular-typeorm#2]
I am using your library but i no have no example to work with this lib, you can hive me some example in an angular component, thanks

**Comment by arslanmughal99** [comment]
You can initialize connection  in your AppModule like this 
```ts
import { AngularTypeormModule } from 'angular-typeorm';

@NgModule({
  declarations: [],
  imports: [
    AngularTypeormModule.forRoot({
        // Put your typeorm
        // connection options here  
    })
  ],
  providers: [],
  bootstrap: [AppComponent]
})

export class AppModule {}
```

And to use connection in your angular services you can import connection from  typeorm directly like this.
[https://typeorm.io/#/connection-api](https://typeorm.io/#/connection-api)
```ts
import {getConnection} from "typeorm";

const connection = getConnection();
```

**Comment by cberenguer** [comment]
Yes i did this but look the error that i have
![image](https://user-images.githubusercontent.com/16119930/121209835-30185180-c849-11eb-8d67-4b655abfa22c.png)
angular + electron

**Comment by cberenguer** [comment]
module configuration
```ts
AngularTypeormModule.forRoot({
      type: 'sqlite',
      database: 'dist/assets/database.db',
      entities: [
        __dirname + '/entity/*.ts'
      ],
      synchronize: true,
    })
```

**Comment by arslanmughal99** [comment]
For electron you can use this boilerplate 
[https://github.com/arslanmughal99/angular-electron-typeorm](https://github.com/arslanmughal99/angular-electron-typeorm)

**Comment by arslanmughal99** [comment]
Make sure to replace pg with sqlite in the `angular.webpack.js`
